### ISSUE TITLE
Received issue; j2net.runtime could not be found

### ISSUE THREAD

**Issue by imkhairulikhwan** [chequer-io/J2NET#1]
Hi! I tried to integrate JDBC.NET to my .NET Core 6 application. However, after following the steps in Getting Started, I ran the sample codes and after hitting connection.Open(), I received the above error. 

The full message would be "j2net.runtime could not be found. please check if the runtime is installed for your platform."

I have double-checked in the config as well and it seems fine. 

Worth to take note is I upgraded the version from .NET Core 2.1 to 6 prior to integrating the code. 

Thank you!

**Comment by holiday1228** [comment]
Hi, I also got similiar situation. 

I always recieve error message "j2net.runtime could not be found. please check if the runtime is installed for your platform." when I running debug with VS2022 on Windows. But in Ubuntu, it not always happen. I use same code and settings in each environment.

By the way, my project is upgraded from .NET Core 3.1 to NET 6. 

Thanks.

**Comment by natilivni** [comment]
I am having this issue on .net7.  Any ideas?

**Comment by louissimps** [comment]
> I am having this issue on .net7. Any ideas?

Did you come up with any resolution on this?

**Comment by evan-choi** [comment]
@imkhairulikhwan 
Please tell us the commit hash, os, architecture you tested

@natilivni @louissimps @holiday1228 
We will also update the TargetFramework of the J2NET.Sample project to .net 7.0 in the next version.

**Comment by evan-choi** [comment]
Hopefully this issue will be fixed in version [1.3.0](https://github.com/chequer-io/J2NET/releases/tag/v1.3.0).
If you encounter the same problem again, please write a new issue.
thank you

**Comment by evan-choi** [comment]
Hopefully this issue will be fixed in version [1.3.0](https://github.com/chequer-io/J2NET/releases/tag/v1.3.0).
If you encounter the same problem again, please write a new issue.
thank you
